//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjGaragem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Venda
    {
        public string Id { get; set; }
        public string Carro { get; set; }
        public string Cliente { get; set; }
        public string Funcionario { get; set; }
        public string Descricao { get; set; }
    
        public virtual TB_CARRO TB_CARRO { get; set; }
        public virtual TB_CLIENTE TB_CLIENTE { get; set; }
        public virtual TB_FUNCIONARIO TB_FUNCIONARIO { get; set; }
    }
}
